fstCopy_Proj5/fstCopy_Proj5/Models/DATE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fstCopy_Proj5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATE
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> startDateNominate { get; set; }
        public Nullable<System.DateTime> EndDateNominate { get; set; }
        public Nullable<System.DateTime> startDateOfElection { get; set; }
        public Nullable<System.DateTime> EndDateOfElection { get; set; }
    }
}

fstCopy_Proj5/fstCopy_Proj5/Controllers/DATEsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using fstCopy_Proj5.Models;

namespace fstCopy_Proj5.Controllers
{
    public class DATEsController : Controller
    {
        private ElectionEntities db = new ElectionEntities();


        // GET: Dates
        public ActionResult Index()
        {
            return View(db.DATES.ToList());
        }

        public ActionResult IndexAdmin()
        {
            return View(db.DATES.ToList());
        }

        // GET: Dates/Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,startDateNominate,EndDateNominate,startDateOfElection,EndDateOfElection")] DATE dateModel)
        {
            if (ModelState.IsValid)
            {
                db.DATES.Add(dateModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dateModel);
        }

        // GET: Dates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DATE dateModel = db.DATES.Find(id);
            if (dateModel == null)
            {
                return HttpNotFound();
            }
            return View(dateModel);
        }

        // POST: Dates/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,startDateOfElection,EndDateOfElection")] DATE dateModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dateModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dateModel);
        }

        // GET: Dates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DATE dateModel = db.DATES.Find(id);
            if (dateModel == null)
            {
                return HttpNotFound();
            }
            return View(dateModel);
        }

        // POST: Dates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DATE dateModel = db.DATES.Find(id);
            db.DATES.Remove(dateModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

fstCopy_Proj5/fstCopy_Proj5/Views/DATEs/Create.cshtml
@model fstCopy_Proj5.Models.DATE



<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>تحديد موعد الانتخابات</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <style>
        body {
            direction: rtl;
            text-align: right;
        }

        .custom-form .control-label {
            text-align: right;
            float: right;
        }

        .custom-form .form-group {
            margin-bottom: 15px;
        }

        .custom-form .btn-center {
            display: flex;
            justify-content: center;
        }

        .custom-form .text-center {
            text-align: center;
        }

        .custom-form .form-group label {
            font-weight: bold;
        }

        .container {
            margin-top: 50px;
        }
    </style>
</head>
<body>
    <div class="container custom-form">
        <h2 class="text-center">تحديد موعد الانتخابات</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <label class="control-label col-md-2">بداية الترشيح</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.startDateNominate, new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
                        @Html.ValidationMessageFor(model => model.startDateNominate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">نهاية الترشيح</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EndDateNominate, new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
                        @Html.ValidationMessageFor(model => model.EndDateNominate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">بداية الانتخابات</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.startDateOfElection, new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
                        @Html.ValidationMessageFor(model => model.startDateOfElection, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">نهاية الانتخابات</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EndDateOfElection, new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
                        @Html.ValidationMessageFor(model => model.EndDateOfElection, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group btn-center">
                    <div class="col-md-12">
                        <input type="submit" value="إضافة" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }
    </div>
</body>
</html>

fstCopy_Proj5/fstCopy_Proj5/Views/DATEs/Delete.cshtml
@model fstCopy_Proj5.Models.DATE

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DATE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.startDateNominate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startDateNominate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDateNominate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDateNominate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.startDateOfElection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startDateOfElection)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDateOfElection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDateOfElection)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

fstCopy_Proj5/fstCopy_Proj5/Views/DATEs/Details.cshtml
@model fstCopy_Proj5.Models.DATE

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DATE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.startDateNominate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startDateNominate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDateNominate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDateNominate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.startDateOfElection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startDateOfElection)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDateOfElection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDateOfElection)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

fstCopy_Proj5/fstCopy_Proj5/Views/DATEs/Edit.cshtml
@model fstCopy_Proj5.Models.DATE

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";

}

<h2 class="text-center mb-4">Edit Election Dates</h2>

@using (Html.BeginForm("IndexAdmin", "DATEs"))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <h4>Edit Date</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group row">
            @Html.LabelFor(model => model.startDateNominate, htmlAttributes: new { @class = "col-sm-3 col-form-label" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.startDateNominate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.startDateNominate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.EndDateNominate, htmlAttributes: new { @class = "col-sm-3 col-form-label" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.EndDateNominate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDateNominate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.startDateOfElection, htmlAttributes: new { @class = "col-sm-3 col-form-label" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.startDateOfElection, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.startDateOfElection, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.EndDateOfElection, htmlAttributes: new { @class = "col-sm-3 col-form-label" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.EndDateOfElection, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDateOfElection, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

fstCopy_Proj5/fstCopy_Proj5/Views/DATEs/Index.cshtml
@model IEnumerable<fstCopy_Proj5.Models.DATE>

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="card mb-4">
        <div class="card-body">
            @foreach (var item in Model)
            {
                <div class="row mb-2">
                    <div class="col-md-6">
                        <p class="card-text">
                            <strong>تاريخ بدء الترشح:</strong> @Html.DisplayFor(modelItem => item.startDateNominate)
                        </p>
                    </div>
                    <div class="col-md-6">
                        <p class="card-text">
                            <strong>تاريخ نهاية الترشح:</strong> @Html.DisplayFor(modelItem => item.EndDateNominate)
                        </p>
                    </div>
                    <div class="col-md-6">
                        <p class="card-text">
                            <strong>تاريخ بداية الانتخابات:</strong> @Html.DisplayFor(modelItem => item.startDateOfElection)
                        </p>
                    </div>
                    <div class="col-md-6">
                        <p class="card-text">
                            <strong>تاريخ نهاية الانتخابات:</strong> @Html.DisplayFor(modelItem => item.EndDateOfElection)
                        </p>
                    </div>
                </div>
                <hr />
            }
        </div>
    </div>
</div>

fstCopy_Proj5/fstCopy_Proj5/Views/DATEs/IndexAdmin.cshtml
@model IEnumerable<fstCopy_Proj5.Models.DATE>

@{
    ViewBag.Title = "IndexAdmin";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}

<h2 class="text-center mb-4">Election Dates</h2>

<p class="text-right mb-3">
    @Html.ActionLink("Create New", "Create", new { @class = "btn btn-primary" })
</p>

<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>وقت بداية الترشح</th>
            <th>وقت نهاية الترشح</th>
            <th>وقت بداية الانتخابات </th>
            <th>وقت نهاية الانتخابات</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.startDateNominate)</td>
                <td>@Html.DisplayFor(modelItem => item.EndDateNominate)</td>
                <td>@Html.DisplayFor(modelItem => item.startDateOfElection)</td>
                <td>@Html.DisplayFor(modelItem => item.EndDateOfElection)</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-warning btn-sm" }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-info btn-sm" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger btn-sm" })
                </td>
            </tr>
        }
    </tbody>
</table>

<style>
    .table th, .table td {
        text-align: center;
    }

    .table th {
        background-color: #343a40;
        color: #fff;
    }

    .table td a {
        margin: 0 5px;
    }
</style>